services:

  test_db:
    image: mysql:8.0
    ports:
      - 3307:3307
    networks:
      - test
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: eventmanager_test
    command: --port=3307

  test_backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - test
    depends_on:
      - test_db
    environment:
      DATABASE_USERNAME: ${DB_HOST}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: db
      TEST_DATABASE_HOST: test_db
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      RAILS_ENV: test
    command:  >
      sh -c "
        rm -f tmp/pids/server.pid &&
        until mysql -h db -u ${DB_HOST} -p ${DB_PASSWORD} -e 'select 1' &> /dev/null; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done &&
        bundle exec rake db:create &&
        bundle exec rake db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "


networks:
  test: