services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - test
    environment:
      POSTGRES_DB: eventmanager_test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d eventmanager_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/eventmanager_test
      DATABASE_HOST: db
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      SQL_DATABASE: eventmanager_test
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      RAILS_ENV: test
    command:  >
      sh -c "
        echo 'in docker-compose test yaml file' &&
        bundle exec rake db:create &&
        bundle exec rake db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails test
      "

networks:
  test:
