services:

  frontend:
    build: ./frontend
    ports:
      - 3001:3001
    networks:
      - dev
    environment:
      REACT_APP_BACKEND_DEV_URL: ${BACKEND_DEV_URL}

  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - dev
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: db
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    command:  >
      sh -c "
        rm -f tmp/pids/server.pid &&
        until mysql -h db -u $DATABASE_USERNAME -p$DATABASE_PASSWORD -e 'select 1' &> /dev/null; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done &&
        bundle exec rake db:create &&
        bundle exec rake db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "

  db:
    image: mysql:8.0
    volumes:
      - event_db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: eventmanager_development

volumes:
  event_db:
networks:
  dev:
