name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up docker images
        run: |
          docker compose -f docker-compose.test.yaml build --no-cache

      - name: Running tests
        run: |
          docker compose -f docker-compose.test.yaml up test_backend

  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Heroku container registry
        run: |
          echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}

      - name: Build and push Docker images to registry
        run: |
          docker build -t registry.heroku.com/event-manager-ruby/web ./backend
          docker push registry.heroku.com/event-manager-ruby/web

      - name: Release backend image
        run: |
          heroku stack:set container --app event-manager-ruby
          heroku container:release web --app event-manager-ruby
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          RAILS_ENV: production

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Heroku container registry
        run: |
          echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}

      - name: Build and push Docker images to registry
        run: |
          docker build -t registry.heroku.com/event-manager-frontend/web ./frontend
          docker push registry.heroku.com/event-manager-frontend/web

      - name: Release frontend image
        run: |
          heroku stack:set container --app event-manager-frontend
          heroku container:release web --app event-manager-frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
