name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - bane: Checkout code
    - uses: actions/checkout@v4

    - name: Docker compose build
    - run: docker compose build --no-cache
      

